# Preprocessing

In [10]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from src.preprocessing import save_processed_data, get_df_engineered

In [11]:
save_processed_data()

In [12]:
df = pd.read_csv("../data/processed/df_processed.csv")
df

,account_length,area_code,international_plan,voice_mail_plan,number_vmail_messages,total_day_minutes,total_day_calls,total_day_charge,total_eve_minutes,total_eve_calls,total_eve_charge,total_night_minutes,total_night_calls,total_night_charge,total_intl_minutes,total_intl_calls,total_intl_charge,customer_service_calls,churn
0,128,1,0,1,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False
1,107,1,0,1,26,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False
2,137,1,0,0,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False
3,84,0,1,0,0,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False
4,75,1,1,0,0,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2661,79,1,0,0,0,134.7,98,22.90,189.7,68,16.12,221.4,128,9.96,11.8,5,3.19,2,False
2662,192,1,0,1,36,156.2,77,26.55,215.5,126,18.32,279.1,83,12.56,9.9,6,2.67,2,False
2663,68,1,0,0,0,231.1,57,39.29,153.4,55,13.04,191.3,123,8.61,9.6,4,2.59,3,False
2664,28,2,0,0,0,180.8,109,30.74,288.8,58,24.55,191.9,91,8.64,14.1,6,3.81,2,False
2665,74,1,0,1,25,234.4,113,39.85,265.9,82,22.60,241.4,77,10.86,13.7,4,3.70,0,False

## Feature Engineering

In [4]:
df_engineered = get_df_engineered(df)
df_engineered

,account_length,area_code,international_plan,voice_mail_plan,number_vmail_messages,total_day_minutes,total_day_calls,total_day_charge,total_eve_minutes,total_eve_calls,...,high_usage_service_risk,intl_plan_no_vmail,day_charge_per_minute,eve_charge_per_minute,night_charge_per_minute,intl_charge_per_minute,has_vmail_usage,vmail_plan_unused,new_customer,long_tenure
0,128,1,0,1,25,265.1,110,45.07,197.4,99,...,False,False,0.170011,0.085005,0.044994,0.270000,True,False,False,True
1,107,1,0,1,26,161.6,123,27.47,195.5,103,...,False,False,0.169988,0.085013,0.045008,0.270073,True,False,False,True
2,137,1,0,0,0,243.4,114,41.38,121.2,110,...,False,False,0.170008,0.084983,0.045018,0.269672,False,False,False,True
3,84,0,1,0,0,299.4,71,50.90,61.9,88,...,False,False,0.170007,0.084976,0.044997,0.269697,False,False,False,True
4,75,1,1,0,0,166.7,113,28.34,148.3,122,...,False,False,0.170006,0.085030,0.044997,0.270297,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2661,79,1,0,0,0,134.7,98,22.90,189.7,68,...,False,False,0.170007,0.084976,0.044986,0.270339,False,False,False,True
2662,192,1,0,1,36,156.2,77,26.55,215.5,126,...,False,False,0.169974,0.085012,0.045002,0.269697,True,False,False,True
2663,68,1,0,0,0,231.1,57,39.29,153.4,55,...,False,False,0.170013,0.085007,0.045008,0.269792,False,False,False,True
2664,28,2,0,0,0,180.8,109,30.74,288.8,58,...,False,False,0.170022,0.085007,0.045023,0.270213,False,False,True,False
2665,74,1,0,1,25,234.4,113,39.85,265.9,82,...,False,False,0.170009,0.084994,0.044988,0.270073,True,False,False,True

In [5]:
df_engineered.to_csv("../data/processed/df_engineered.csv", index=False)