In [1]:
import pandas as pd

df = pd.read_csv("data/raw/orders.csv")
df

,order_id,customer_id,order_date,ship_date,delivery_date,customer_name,customer_segment,customer_country,customer_city,customer_region,...,tax_amount,total_order_value,profit,shipping_method,delivery_status,payment_method,payment_status,sales_channel,customer_acquisition_channel,campaign
0,ORD1000000,CUST101392,2025-10-28,2025-10-28,2025-10-28,Thomas Moore,Consumer,United States,Los Angeles,North America,...,4.96,98.95,24.87,Same-Day,On Time,DEBIT CARD,Paid,Mobile App,Organic Search,NaN
1,ORD1000001,CUST117918,2025-04-22,2025-04-23,2025-04-26,Cassandra Hays,Consumer,United States,Houston,North America,...,10.96,172.91,52.96,Standard,On Time,Credit Card,Pending,Mobile App,Organic Search,NaN
2,ORD1000002,CUST111893,2025-08-01,2025-08-02,NaN,Steven Torres,Corporate,United States,Houston,North America,...,16.72,255.64,71.17,Standard,In Transit,PayPal,Paid,Marketplace,Social Media,NaN
3,ORD1000003,CUST110447,2025-11-24,2025-11-26,2025-11-28,Michelle Franco,Consumer,United States,Houston,North America,...,6.76,109.43,46.55,Standard,Delayed,Gift Card,Paid,Website,Email Marketing,BLACKFRIDAY25
4,ORD1000004,CUST102862,2025-01-15,2025-01-16,2025-01-18,Taylor Brown,Small Business,United States,New York,North America,...,3.55,60.04,14.76,Standard,On Time,Debit Card,Paid,Website,Email Marketing,LOYALTY_REWARDS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50120,ORD1027678,CUST132003,2024-01-15,2024-01-15,2024-01-15,Barbara Dalton,Consumer,United States,Los Angeles,North America,...,6.77,125.05,47.48,Same-Day,Delayed,Credit Card,Paid,Website,Organic Search,NaN
50121,ORD1010704,CUST101039,2024-04-02,2024-04-02,2024-04-02,Bradley Montgomery,Consumer,United States,New York,North America,...,3.62,80.55,7.13,Same-Day,On Time,Debit Card,Paid,Website,Organic Search,NaN
50122,ORD1033461,CUST128428,2026-04-25,2026-04-26,2026-04-29,Christina Swanson,Consumer,United States,Los Angeles,North America,...,6.31,103.85,40.24,Standard,On Time,PayPal,Paid,Website,Organic Search,NaN
50123,ORD1022001,CUST105020,2024-02-04,2024-02-04,2024-02-09,Tammy Booker,Corporate,Canada,Vancouver,North America,...,25.56,222.14,58.81,Standard,On Time,PayPal,Paid,Website,Organic Search,NaN
50124,ORD1030170,CUST122477,2024-10-26,2024-10-26,2024-10-29,Teresa Jones,Corporate,Australia,Sydney,Oceania,...,16.81,190.97,45.58,Standard,On Time,PayPal,Paid,Mobile App,Paid Ads,BLACKFRIDAY25

In [7]:
df.isnull()

,order_id,customer_id,order_date,ship_date,delivery_date,customer_name,customer_segment,customer_country,customer_city,customer_region,...,tax_amount,total_order_value,profit,shipping_method,delivery_status,payment_method,payment_status,sales_channel,customer_acquisition_channel,campaign
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
2,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50120,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
50121,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
50122,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
50123,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
50124,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False