In [1]:
import pandas as pd
import numpy

df = pd.read_csv("data/raw/orders.csv")

# deduplication (exact duplicates)
df = df.drop_duplicates(keep="first", ignore_index=True)

# handle datetime data types
df['order_date'] = pd.to_datetime(df['order_date'], format="mixed")
df['ship_date'] = pd.to_datetime(df['ship_date'], format="mixed")
df['delivery_date'] = pd.to_datetime(df['delivery_date'], format="mixed")


# normalizing text data and handling categorical data types
df['customer_name'] = df['customer_name'].str.strip().str.lower()
df['customer_segment'] = df['customer_segment'].str.lower().astype("category")
df['customer_country'] = df['customer_country'].replace(
    {"USA": "United States"}
).str.lower().astype("category")
df['customer_city'] = df['customer_city'].str.lower().astype("category")
df['customer_region'] = df['customer_region'].str.lower().astype("category")
df['order_status'] = df['order_status'].str.lower().astype("category")
df['shipping_method'] = df['shipping_method'].str.lower().astype("category")
df['delivery_status'] = df['delivery_status'].str.lower().astype("category")
df['payment_method'] = df['payment_method'].str.lower().astype("category")
df['payment_status'] = df['payment_status'].str.lower().astype("category")
df['sales_channel'] = df['sales_channel'].str.lower().astype("category")
df['customer_acquisition_channel'] = df['customer_acquisition_channel'].str.lower().astype("category")
df['campaign'] = df['campaign'].str.lower().astype("category")

df = df.drop(columns="product_categories") # not needed

df.iloc[:, :13]

,order_id,customer_id,order_date,ship_date,delivery_date,customer_name,customer_segment,customer_country,customer_city,customer_region,order_status,total_items,unique_products
0,ORD1000000,CUST101392,2025-10-28,2025-10-28,2025-10-28,thomas moore,consumer,united states,los angeles,north america,delivered,3,3
1,ORD1000001,CUST117918,2025-04-22,2025-04-23,2025-04-26,cassandra hays,consumer,united states,houston,north america,delivered,4,4
2,ORD1000002,CUST111893,2025-08-01,2025-08-02,NaT,steven torres,corporate,united states,houston,north america,shipped,6,6
3,ORD1000003,CUST110447,2025-11-24,2025-11-26,2025-11-28,michelle franco,consumer,united states,houston,north america,delivered,3,2
4,ORD1000004,CUST102862,2025-01-15,2025-01-16,2025-01-18,taylor brown,small business,united states,new york,north america,delivered,4,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,ORD1049995,CUST127169,2024-11-28,2024-11-30,2024-12-02,megan rodriguez md,consumer,germany,berlin,europe,delivered,4,4
49996,ORD1049996,CUST120014,2024-08-16,2024-08-17,2024-08-18,travis long md,small business,united states,chicago,north america,delivered,3,2
49997,ORD1049997,CUST107719,2024-08-29,2024-08-29,NaT,jon holt dds,consumer,united states,NaN,north america,shipped,2,2
49998,ORD1049998,CUST106843,2026-07-31,2026-07-31,2026-08-02,allison lester,corporate,united kingdom,london,europe,delivered,1,1
49999,ORD1049999,CUST130445,2024-11-10,2024-11-11,2024-11-12,angela harper,consumer,germany,munich,europe,returned,3,2

In [2]:
df.iloc[:, 13:]

,subtotal,discount_amount,shipping_cost,tax_amount,total_order_value,profit,shipping_method,delivery_status,payment_method,payment_status,sales_channel,customer_acquisition_channel,campaign
0,70.89,0.00,23.10,4.96,98.95,24.87,same-day,on time,debit card,paid,mobile app,organic search,NaN
1,190.10,33.59,5.44,10.96,172.91,52.96,standard,on time,credit card,pending,mobile app,organic search,NaN
2,278.21,39.29,0.00,16.72,255.64,71.17,standard,in transit,paypal,paid,marketplace,social media,NaN
3,96.50,0.00,6.17,6.76,109.43,46.55,standard,delayed,gift card,paid,website,email marketing,blackfriday25
4,50.65,0.00,5.84,3.55,60.04,14.76,standard,on time,debit card,paid,website,email marketing,loyalty_rewards
...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,41.78,0.00,7.48,7.94,57.20,14.08,standard,on time,paypal,paid,marketplace,paid ads,blackfriday25
49996,141.65,18.58,17.46,8.61,149.14,34.55,express,on time,credit card,paid,mobile app,direct,NaN
49997,121.74,0.00,0.00,8.52,130.26,46.08,standard,in transit,credit card,paid,website,paid ads,summer_sale24
49998,6.38,0.00,5.93,1.28,13.59,2.03,standard,on time,debit card,paid,mobile app,direct,NaN
49999,157.99,24.71,0.00,25.32,158.60,53.14,express,returned,bank transfer,refunded,mobile app,email marketing,NaN